version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGODB_URL: "mongodb://mongodb:27017/app"
      NODE_ENV: "production"
      ACCESS_SECRET_KEY: "ACCESS_SECRET_KEY"
      REFRESH_SECRET_KEY: "REFRESH_SECRET_KEY"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
      - mongodb